plugins {
    alias(libs.plugins.android.library)
}

android {
    compileSdk = 37

    defaultConfig {
        minSdkVersion 21
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        javaCompileOptions {
            annotationProcessorOptions {
                arguments += ["room.schemaLocation":
                                      "$projectDir/schemas".toString()]
            }
        }
    }

    sourceSets {
        // Adds exported schema location as test app assets.
        androidTest.assets.srcDirs += files("$projectDir/schemas".toString())
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        // Flag to enable support for the new language APIs
        coreLibraryDesugaringEnabled true

        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'm.co.rh.id.a_news_provider.base'
    buildFeatures {
        buildConfig true
    }
    lint {
        abortOnError = true
        warningsAsErrors = false
    }
}

dependencies {
    coreLibraryDesugaring libs.desugar.jdk.libs

    implementation libs.room.runtime
    implementation libs.concurrent.utils
    annotationProcessor libs.room.compiler

    api libs.androidx.annotation
    api libs.a.provider
    api libs.a.navigator
    api libs.a.logger
    api libs.rx.utils
    api libs.rxandroid
    api libs.rxjava // can't update this, minSdk must be 21

    testImplementation libs.junit
    androidTestImplementation libs.junit
    androidTestImplementation libs.androidx.test.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.room.testing
}