name: Android Release APKs

on:
 push:
  tags:
   - v*
   
jobs:
  release-apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
          cache: gradle
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build
        env:
          ALIAS: ${{secrets.ALIAS}}
          KEY_PASSWORD: ${{secrets.KEY_PASSWORD}}
          KEY_STORE_PASSWORD: ${{secrets.KEY_STORE_PASSWORD}}
          SIGNING_KEY: ${{secrets.SIGNING_KEY}}
      - name: Create Github Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          body_path: ./app/build/changelog.txt
          files: |
            ./app/build/outputs/apk/debug/app-debug.apk
            ./app/build/outputs/apk/release/app-release.apk
            ./app/build/changelog.txt
